events{}

http{

        server{

                listen 8080;
               # root /usr/share/nginx/html/example.com/;
               location /{
                        proxy_pass http://34.227.11.229;
               }

        }

        server{
          listen 80;
          root /usr/share/nginx/html/example.com/;
          index index.html;

        }

        

}
